[GENERAL]
normal_exit="Program exited normally"

[ERROR]
unknown="Unknown error!"
missing_command="Missing Command!"
no_file_directory="No such file or directory!"
no_command_inputted="User failed to input command!"
unknown_command="Invalid command!"

[COMMAND_OUTPUT]
[COMMAND_OUTPUT.CLEAR]
main="Cleared the screen"

[HELP]
more_info="For more information on a specific command, type HELP command-name"
[HELP.HELP]
main="Shows a list of commands, and a basic explanation of what they do"
[HELP.CD]
main="Change working directory"
[HELP.LIST_DIR]
main="List current directory"
[HELP.CLEAR]
main="Clear the terminal screen"
[HELP.READ]
main="Dump text file contents to terminal screen"
[HELP.PACKAGE]
main="Integration package manager"
[HELP.PACKAGE.SUB]
install="Install a package"
remove="Remove a package"
[HELP.EXIT]
main="Shuts down the program"
[HELP.SYSTEM]
main="Use to configure some system things, be careful!"
[HELP.SYSTEM.SUB]
recursion="Set the recursion limit, you probaly don't need to touch this"