[GENERAL]
normal_exit="Program exited normally"

[ERROR]
unknown="Unknown error!"
missing_command="Missing Command!"
no_command_inputted="User failed to input command!"
unknown_command="Invalid command!"
language_file="There appears to be an issue with the language file!"
missing_arguement="Missing command arguement"
[ERROR.PATH]
invalid="No such file or directory!"
existing="That file or directory already exists!"
not_file="That isn't a file!"
not_dir="That isn't a folder!"
[ERROR.PRIVILEGE]
read_only="That path is read only!"
forbidden="You don't have read or write access!"

[COMMAND_OUTPUT.CLEAR]
main="Cleared the screen"

[COMMAND_OUTPUT.INTEG.RELOAD]
reloading="Reloading INTEGs..."
reloaded="INTEGs Reloaded!"
[COMMAND_OUTPUT.INTEG.LOAD]
main="Loaded <INT> INTEGs!"

[HELP]
more_info="For more information on a specific command, type HELP command-name"
[HELP.HELP]
main="Shows a list of commands, and a basic explanation of what they do"
[HELP.CD]
main="Change working directory"
[HELP.LIST_DIR]
main="List a directory"
[HELP.CLEAR]
main="Clear the terminal screen"
[HELP.READ]
main="Dump text file contents to the terminal screen"
[HELP.HOST_CMD]
main="Run a command on the host shell"
[HELP.PACKAGE]
main="Software integration manager"
install="Install a package"
remove="Remove a package"
[HELP.PRINT]
main="Write some text to the terminal screen"
[HELP.REMOVE_DIRECTORY]
main="Delete a directory"
[HELP.MAKE_DIRECTORY]
main="Create a directory"
[HELP.REMOVE_FILE]
main="Delete a file"
[HELP.USER_INPUT]
main="Wait for user input"
[HELP.REFERENCE_SCRIPT]
main="Reference a script file (.mshell)"
[HELP.EXIT]
main="Shuts down the program"
