[GENERAL]
normal_exit="Program exited normally"

[ERROR]
unknown="Unknown error!"
missing_command="Missing Command!"
invalid_path="No such file or directory!"
existing_path="That file or directory already exists!"
no_command_inputted="User failed to input command!"
unknown_command="Invalid command!"
language_file="There appears to be an issue with the language file!"
missing_arguement="Missing command arguement"

[COMMAND_OUTPUT]
[COMMAND_OUTPUT.CLEAR]
main="Cleared the screen"

[HELP]
more_info="For more information on a specific command, type HELP command-name"
[HELP.HELP]
main="Shows a list of commands, and a basic explanation of what they do"
[HELP.CD]
main="Change working directory"
[HELP.LIST_DIR]
main="List a directory"
[HELP.CLEAR]
main="Clear the terminal screen"
[HELP.READ]
main="Dump text file contents to the terminal screen"
[HELP.HOST_CMD]
main="Run a command on the host shell"
[HELP.PACKAGE]
main="Software integration manager"
[HELP.PACKAGE.SUB]
install="Install a package"
remove="Remove a package"
[HELP.PRINT]
main="Write some text to the terminal screen"
[HELP.EXIT]
main="Shuts down the program"
[HELP.SYSTEM]
main="Use to configure some system things, be careful!"
[HELP.SYSTEM.SUB]
recursion="Set the recursion limit, you probaly don't need to touch this"