[GENERAL]
normal_exit="lang['GENERAL']['normal_exit']"

[ERROR]
unknown="lang['ERROR']['unknown']"
missing_command="lang['ERROR']['missing_command']"
invalid_path="lang['ERROR']['invalid_path']"
existing_path="lang['ERROR']['existing_path']"
no_command_inputted="lang['ERROR']['no_command_inputted']"
unknown_command="lang['ERROR']['unknown_command']"
language_file="lang['ERROR']['language_file']"
missing_arguement="lang['ERROR']['missing_arguement']"

[COMMAND_OUTPUT]
[COMMAND_OUTPUT.CLEAR]
main="lang['COMMAND_OUTPUT']['CLEAR']['main']"

[HELP]
more_info="lang['HELP']['more_info']"
[HELP.HELP]
main="lang['HELP']['HELP']['main']"
[HELP.CD]
main="lang['HELP']['CD']['main']"
[HELP.LIST_DIR]
main="lang['HELP']['LIST_DIR']['main']"
[HELP.CLEAR]
main="lang['HELP']['CLEAR']['main']"
[HELP.READ]
main="lang['HELP']['READ']['main']"
[HELP.HOST_CMD]
main="lang['HELP']['HOST_CMD']['main']"
[HELP.PACKAGE]
main="lang['HELP']['PACKAGE']['main']"
[HELP.PACKAGE.SUB]
install="lang['HELP']['PACKAGE']['SUB']['install']"
remove="lang['HELP']['PACKAGE']['SUB']['remove']"
[HELP.PRINT]
main="lang['HELP']['PRINT']['main']"
[HELP.USER_INPUT]
main="lang['HELP']['USER_INPUT']['main']"
[HELP.EXIT]
main="lang['HELP']['EXIT']['main']"
[HELP.SYSTEM]
main="lang['HELP']['SYSTEM']['main']"
[HELP.SYSTEM.SUB]
recursion="lang['HELP']['SYSTEM']['SUB']['recursion']"
[HELP.REMOVE_DIRECTORY]
main="lang['HELP']['REMOVE_DIRECTORY']['main']"
[HELP.MAKE_DIRECTORY]
main="lang['HELP']['MAKE_DIRECTORY']['main']"
[HELP.REMOVE_FILE]
main="lang['HELP']['REMOVE_FILE']['main']"